language: cpp

sudo: enabled
dist: xenial

compiler:
  - gcc

matrix:
  include:
    - name: CUDA 8
      env:
      - CUDA=8.0.61-1
      - CUDA_SHORT=8.0
      - CUDA_APT=8-0
    - name: CUDA 9
      env:
      - CUDA=9.2.148-1
      - CUDA_SHORT=9.2
      - CUDA_APT=9-2
    - name: CUDA 10
      env:
      - CUDA=10.1.105-1
      - CUDA_APT=10-1
      - CUDA_SHORT=10.1

before_install:
  - INSTALLER=cuda-repo-ubuntu1604_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - sudo apt-get update -qq
  - sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT} --allow-unauthenticated
  - sudo apt-get clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - PATH=${PATH}:${PWD}

before_script:
    - mkdir build
    - cd build
    - cmake .. -GNinja

script: ninja
